name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.27.0'

      - name: Configure
        run: cmake . -B build

      - name: Build
        run: cmake --build build/

      - name: Test (Linux)
        if: runner.os == 'Linux'
        run: |
          ./build/vstl_demo > ./build/test.out || true
          cat ./build/test.out
          diff -u .github/linux.out ./build/test.out
          
      - name: Test (Windows)
        if: runner.os == 'Windows'
        run: |
          ./build/vstl_demo.exe > ./build/test.out || true
          type ./build/test.out
          diff -u .github/windows.out ./build/test.out